// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRU-etgd9jy5DDHm-cNp6Ulc1seZh71XM',
    appId: '1:370681971963:web:3b0ce9ee3e541254019c5e',
    messagingSenderId: '370681971963',
    projectId: 'worship-charts-c0b65',
    authDomain: 'worship-charts-c0b65.firebaseapp.com',
    storageBucket: 'worship-charts-c0b65.firebasestorage.app',
    measurementId: 'G-5GRZDD6DY5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3jOi14s2ODNfNKiH02ztNaR6Uqy5b1UY',
    appId: '1:370681971963:android:66056dc1f8122707019c5e',
    messagingSenderId: '370681971963',
    projectId: 'worship-charts-c0b65',
    storageBucket: 'worship-charts-c0b65.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8hXcC77YiDlyFi-M1843hAaKP2fPHcx8',
    appId: '1:370681971963:ios:3b58562506126062019c5e',
    messagingSenderId: '370681971963',
    projectId: 'worship-charts-c0b65',
    storageBucket: 'worship-charts-c0b65.firebasestorage.app',
    iosBundleId: 'com.example.worshipApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8hXcC77YiDlyFi-M1843hAaKP2fPHcx8',
    appId: '1:370681971963:ios:3b58562506126062019c5e',
    messagingSenderId: '370681971963',
    projectId: 'worship-charts-c0b65',
    storageBucket: 'worship-charts-c0b65.firebasestorage.app',
    iosBundleId: 'com.example.worshipApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDRU-etgd9jy5DDHm-cNp6Ulc1seZh71XM',
    appId: '1:370681971963:web:688beb52ef4e2cb2019c5e',
    messagingSenderId: '370681971963',
    projectId: 'worship-charts-c0b65',
    authDomain: 'worship-charts-c0b65.firebaseapp.com',
    storageBucket: 'worship-charts-c0b65.firebasestorage.app',
    measurementId: 'G-CHT5YE6VP4',
  );
}
